In [56]:
import pandas as pd
import numpy as np
import json

In [57]:
df = pd.read_csv("csv/besucherstatistik-alle-vorbereitet.csv", delimiter=";", na_values=["-"])
df

,Institution_11_12,2011,2012,Institution_13_14,2013,2014,Bemerkung_11_12,Bemerkung_13_14,Kategorie,Block
0,Deutsches Theater / Kammerspiele,165.405,162.136,Deutsches Theater / Kammerspiele,189.135,180.769,NaN,NaN,Große Sprechbühnen,1
1,Volksbühne,135.284,143.292,Volksbühne,175.393,170.205,NaN,NaN,Große Sprechbühnen,1
2,Maxim Gorki Theater,92.056,79.984,Maxim Gorki Theater,69.745,101.035,NaN,NaN,Große Sprechbühnen,1
3,Berliner Ensemble,188.406,181.639,Berliner Ensemble,228.207,231.151,NaN,NaN,Große Sprechbühnen,1
4,"Hebbel am Ufer (HAU 1, 2, 3)",89.692,61.963,"Hebbel am Ufer (HAU 1, 2, 3)",65.979,59.830,NaN,NaN,Große Sprechbühnen,1
...,...,...,...,...,...,...,...,...,...,...
127,Tanzfabrik Berlin e.V.,5.789,5.706,Tanzfabrik Berlin e.V.,5.528,6.416,NaN,"Performences sind oft eintrittsfrei, deshalb o...",Spielstättenförderung,10
128,Dock 11,13.803,11.787,Dock 11,11.373,8.400,NaN,"Performences sind oft eintrittsfrei, deshalb o...",Spielstättenförderung,10
129,Laborgras,1.610,963,Laborgras,1.317,204,NaN,"Performences sind oft eintrittsfrei, deshalb o...",Spielstättenförderung,10
130,ada Studio & Bühne,1.243,1.077,ada Studio & Bühne,982,1.047,NaN,"Performences sind oft eintrittsfrei, deshalb o...",Spielstättenförderung,10
131,NaN,NaN,NaN,Brotfabrik,NaN,9.883,NaN,"Performences sind oft eintrittsfrei, deshalb o...",Spielstättenförderung,10

In [58]:
# merge institution
institution = df['Institution_13_14'].copy()
institution[institution.isna()] = df['Institution_11_12'][institution.isna()]

df['Institution'] = institution.replace(r'\n',' ', regex=True) 

df = df.drop(columns=['Institution_11_12', 'Institution_13_14'])

In [59]:
# remove leading and trailing whitespaces
df['Kategorie'] = df['Kategorie'].str.strip()

In [60]:
# convert numberical cols

df['Block'] = df['Block'].astype('int8')

num_cols = ['2011','2012','2013', '2014']

if df['2013'][66] == 'geschlossen':
    df.at[66, '2013'] = np.nan

df[num_cols] = df[num_cols].apply(lambda s : s.str.replace('.', '', regex=False), axis=1)
df[num_cols] = df[num_cols].apply(lambda s : s.str.replace(' ', '', regex=False), axis=1)
df[num_cols] = df[num_cols].fillna(0)
df[num_cols] = df[num_cols].astype(int)

In [61]:
locs = pd.read_csv("csv/kultureinrichtungen_alle.csv", delimiter=";", na_values=["-"])
locs['Institution'] = locs['Institution'].replace(r'\n',' ', regex=True)
locs['Institution'] = locs['Institution'].str.strip()

display(locs)

,Institution,Adresse,Lat,Lon,Haltestelle,HaltestelleLat,HaltestelleLon,Entfernung,SUBahn,SUEntfernung,Betreiber,GruppeA,GruppeB
0,Deutsches Theater / Kammerspiele,"Schumannstraße 13,10117 Berlin",52.523917,13.382083,Deutsches Theater,52.523.126,13.383.266,118.0,U Oranienburger Tor,385.0,NaN,Bühnen und Theater,Große Sprechbühnen
1,Volksbühne,"Rosa-Luxemburg-Platz,10178 Berlin",52.527250,13.412389,U Rosa-Luxemburg-Platz,52.528.187,13.410.404,170.0,U Rosa-Luxemburg-Platz,170.0,NaN,Bühnen und Theater,Große Sprechbühnen
2,Maxim Gorki Theater,"Am Festungsgraben 2,10117 Berlin",52.519000,13.395611,Am Kupfergraben,52.519.413,13.395.392,49.0,NaN,NaN,NaN,Bühnen und Theater,Große Sprechbühnen
3,Berliner Ensemble,"Bertolt-Brecht-Platz 1,10117 Berlin",52.522056,13.386417,Am Weidendamm,52.521.912,13.388.452,138.0,S+U Friedrichstr.,204.0,NaN,Bühnen und Theater,Große Sprechbühnen
4,"Hebbel am Ufer (HAU 1, 2, 3)","Hallesches Ufer 32,10963 Berlin",52.499056,13.386194,Willy-Brandt-Haus,5.250.041,13.387.437,173.0,U Möckernbrücke,198.0,NaN,Bühnen und Theater,Große Sprechbühnen
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,Heimathafen Neukölln,"Karl-Marx-Straße 141,12043 Berlin",52.476972,13.439194,U Karl-Marx-Str.,52.476.427,13.439.808,73.0,U Karl-Marx-Str.,73.0,NaN,Förderung,Spielstättenförderung
111,Tanzfabrik Berlin e.V.,"Uferstraße 23,13357 Berlin",52.551778,13.374944,Uferstr.,52.553.258,13.378.169,273.0,U Pankstr.,469.0,NaN,Förderung,Spielstättenförderung
112,Dock 11,"Kastanienallee 79,10435 Berlin",52.536667,13.408028,Schwedter Str.,52.536.834,13.407.959,19.0,U Senefelderplatz,547.0,NaN,Förderung,Spielstättenförderung
113,Laborgras,"Großbeerenstraße 56E, 10965 Berlin",52.496806,13.421389,Kottbusser Brücke,52.495.538,13.420.697,147.0,U Kottbusser Tor,232.0,NaN,Förderung,Spielstättenförderung
114,ada Studio & Bühne,"Uferstraße 8/23, 13357 Berlin",52.551833,13.374417,Uferstr.,52.553.258,13.378.169,299.0,U Nauener Platz,477.0,NaN,Förderung,Spielstättenförderung

# Load and Merge Locations

In [62]:
from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

In [63]:
indices = []

df['foreign_key'] = np.nan

for index, row in df.iterrows():
    # find the most similar location

    idx = np.argmax([row["Institution"].startswith(b) for b in locs["Institution"]])
    if idx == 0:
        if not row["Institution"].startswith(locs["Institution"][0]):
            simi = [similar(row["Institution"], b) for b in locs["Institution"]]
            if np.max(simi) < 0.7:
                print(f'{row["Institution"]} == {locs["Institution"][np.argmax(simi)]} ({max(simi):.2f})?')
                idx = None
            else:
                # "cie. toula limnaios" exists two times in different categories!!!
                if(row['Institution'] == "cie. toula limnaios"):
                    idx = None
                else:
                    idx = np.argmax(simi)

    if idx != None:
        df.at[index, 'foreign_key'] = locs.iloc[idx]['Institution']
    else: 
        df.at[index, 'foreign_key'] = ''
    # break

prime time theater == Maxim Gorki Theater (0.59)?
Käthe-Kollwitz-Museum == Stiftung Georg-Kolbe-Museum (0.54)?
Museum für Vor- und Frühgeschichte im Martin Gropius-Bau == Neues Museum mit Ägyptisches Museum, Museum für Vor- und Frühgeschichte - Museumsinsel (0.56)?
Monster Truck == Theater Thikwà (0.44)?
kaleidoskop == cie toula limnaios (0.34)?
Showcase beat Le Mot == Schlosspark Theater (0.46)?
isabelle Schad == Gob Squad (0.43)?
Kroesinger, Hans-Werner == Hamburger Bahnhof - Tiergarten (0.42)?
make up productions/A. Baehr == ada Studio & Bühne (0.39)?
MS Schrittmacher/M. Stiefermann == Schlossplatztheater (0.40)?
Martin Nachbar == Hans Wurst Nachfahren (0.57)?
Laurent Chétouane == Pfaueninsel (0.43)?
WilhelmGroener == English Theatre Berlin (0.39)?
Christoph Winkler == Sophiensæle (0.50)?
Christina Ciupke == Canstanza Macras (0.38)?
Brotfabrik == ufa-fabrik e.V. (0.48)?

In [64]:
df = df.merge(locs, how='outer', left_on='foreign_key', right_on='Institution')

In [65]:
# Check for Institutions without any data
np.setdiff1d(locs['Institution'].values, df['foreign_key'].values)

array([], dtype=object)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 132 entries, 0 to 131
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   2011             132 non-null    int64
 1   2012             132 non-null    int64
 2   2013             132 non-null    int64
 3   2014             132 non-null    int64
 4   Bemerkung_11_12  19 non-null     object
 5   Bemerkung_13_14  46 non-null     object
 6   Kategorie        130 non-null    object
 7   Block            132 non-null    int8
 8   Institution_x    132 non-null    object
 9   foreign_key      132 non-null    object
 10  Institution_y    115 non-null    object
 11  Adresse          115 non-null    object
 12  Lat              115 non-null    float64
 13  Lon              115 non-null    float64
 14  Haltestelle      114 non-null    object
 15  HaltestelleLat   114 non-null    object
 16  HaltestelleLon   114 non-null    object
 17  Entfernung       114 non-null    float64
 18  SUBahn           91 non-null     object
 19  SUEntfernung     91 non-null     float64
 20  Betreiber        7 non-null      object
 21  GruppeA          115 non-null    object
 22  GruppeB          115 non-null    object
dtypes: float64(4), int64(4), int8(1), object(14)
memory usage: 23.8+ KB

In [67]:
df['SUEntfernung'] = df['SUEntfernung'].astype(float)

In [68]:
# Fill in missing GruppeA values
GruppeA = df[['Block', 'GruppeA']].dropna().groupby(by='Block')['GruppeA'].unique().apply(lambda x: x[0])
display(GruppeA)
df['GruppeA'] = GruppeA[df['Block']].reset_index()['GruppeA']

Block
1                                    Bühnen und Theater
2                                       Opern und Chöre
3                                    Literatur und Kino
4                                 Berliner Landesmuseen
5     Staatliche Museen zu Berlin / Stiftung Preußis...
6                         Preußische Schlösser & Gärten
7                                         Gedenkstätten
8                                        Bildende Kunst
9                                 Archive/Bibliotheken
10                                            Förderung
Name: GruppeA, dtype: object

In [69]:
# check alignment of Kategorie and GruppeB
df[df['Kategorie'] != df['GruppeB']][['Kategorie', 'GruppeB']]

,Kategorie,GruppeB
9,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
10,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
11,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
12,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
13,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
14,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
15,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
16,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
17,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
18,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
19,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
20,Konzeptgeförderte Theater und Theater-/Tanzgru...,Konzeptgeförderte Theater und Theater-/Tanzgru...
21,Konzeptgeförderte Theater und Theater-/Tanzgru...,NaN
22,Konzeptgeförderte Theater und Theater-/Tanzgru...,NaN
23,Berliner Landesmuseen,NaN
24,Staatliche Museen zu Berlin / Stiftung Preußis...,NaN
25,NaN,NaN
26,NaN,NaN
27,Basisförderung,NaN
28,Basisförderung,NaN
29,Basisförderung,NaN
30,Basisförderung,NaN
31,Basisförderung,NaN
32,Basisförderung,NaN
33,Basisförderung,NaN
34,Basisförderung,NaN
35,Basisförderung,NaN
36,Basisförderung,NaN
37,Spielstättenförderung,NaN
38,Konzeptgeförderte Theater und Theater-/Tanzgru...,Friedrichstadt-Palast
39,Konzeptgeförderte Theater und Theater-/Tanzgru...,Sasha Waltz & Guests
40,Konzeptgeförderte Theater und Theater-/Tanzgru...,Jüdisches Theater
102,Archive/Bibliotheken,Archive/Bibliotheken
103,Archive/Bibliotheken,Archive/Bibliotheken

In [70]:
# Extract and translate zip code

df['PLZ'] = df['Adresse'].str.extract(r'(\d{5}\-?\d{0,4})')

with open("plz.txt") as f:

    zip2district = {}

    district = ""
    for line in f.readlines():

        if line.startswith("Postleitzahlen in"):
            district = line.replace("Postleitzahlen in ", "").strip()
        if line.startswith("1"):
            for n in list(
                map(int, line.replace("\n", "").replace(".", ",").split(", "))
            ):
                zip2district[n] = district

    df['Bezirk'] = df['PLZ'].astype(float).map(zip2district).fillna(df['PLZ'])

# Write to JSON

In [71]:
df = df.where(pd.notnull(df), None)
# df = df.set_index('Institution')
d = df.to_dict(orient='index')

with open('data.json', 'w', encoding='utf-8') as f:
    json.dump(d, f, ensure_ascii=False, indent=4)